sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - npm install coveralls
script:
  - npm run flow-typed-install
  - npm run flow-check
  - npm test
after_success:
  - npm run coveralls
